"""table_users

Revision ID: 069708c5fb85
Revises:
Create Date: 2025-07-11 08:25:04.223275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.app.user.data.user_status import UserStatus
from src.core.db.decorator.int_enum import IntEnum

# revision identifiers, used by Alembic.
revision: str = "069708c5fb85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=70), nullable=False),
        sa.Column("second_name", sa.String(length=70), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("status", IntEnum(UserStatus), nullable=False),
        sa.Column("hash_password", sa.String(length=150), nullable=False),
        sa.Column("session", sa.String(length=50), nullable=True),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
