"""table_user_notifications

Revision ID: b93dc09d2e0c
Revises: 069708c5fb85
Create Date: 2025-07-13 08:28:27.943500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.app.user_notification.data.user_notification_status import UserNotificationStatus
from src.core.db.decorator.int_enum import IntEnum

# revision identifiers, used by Alembic.
revision: str = "b93dc09d2e0c"
down_revision: Union[str, Sequence[str], None] = "069708c5fb85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("status", IntEnum(UserNotificationStatus), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_notifications_created_at"), "user_notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_notifications_status"), "user_notifications", ["status"], unique=False)
    op.alter_column(
        "users", "updated_at", existing_type=mysql.DATETIME(), server_default=sa.text("now()"), existing_nullable=False
    )
    op.alter_column(
        "users", "created_at", existing_type=mysql.DATETIME(), server_default=sa.text("now()"), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_user_notifications_status"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_created_at"), table_name="user_notifications")
    op.drop_table("user_notifications")
    # ### end Alembic commands ###
